### PR TITLE
Write test to find objects or add keys on GraphQL APIs

### PR DESCRIPTION
**Pull request by AaryaZ**
This PR closes [#107](https://github.com/akto-api-security/akto/issues/107).
This pull request addresses Issue #107, which involves the addition of keys and finding objects that were in create-obj request or adding keys that are in response to some other API calls.

Validation: If the application responds with an exception trace or error response strings, it is considered a vulnerability.

The new test is structured and designed to take the objects, object keys, and new keys and use mutations to get keys from the response. It aligns with the objectives of Issue #107.

Please review this PR and provide feedback.

### CODE REVIEW

**Comment by AaryaZ** [comment]
@avneesh-akto I request you to review this PR as early as possible since there are only two days left for hacktober. Also suggest changes if any that need to be addressed.

**Comment by avneesh-akto** [comment]
What is this file? [Security-Misconfiguration/reate-object-add-keys-verify.js](https://github.com/akto-api-security/tests-library/pull/39/files#diff-7967716c4248048ba3f071b4316166d0f7299c605b0ba8295be4083e9fb3bc9c). Please run yaml files on sample API before requesting review

**Comment by AaryaZ** [comment]
@avneesh-akto That was a silly thing on my side. This file was unnecesary. It was performing unit test to find objects or add keys in graphql Api using jest. There was nothing wrong or errorenous in this file. Removed because asked to be removed.
Also i have tested the ayml file in akto.io environment.

**Comment by AaryaZ** [comment]
Also can You add `hacktoberfest` label on it.

**Comment by AaryaZ** [comment]
@avneesh-akto @Ankita28g are there any changes that need to be done in this PR?

**Pull request closed without merging**
